[package]
name = "phonelib"
version = "0.1.4.1"
edition = "2021"
authors = ["Mohamad Al Zohbie <alzoubi528@gmail.com>"]
repository = "https://github.com/mohamadzoh/phonelib"
description = "A library that helps you work with phone numbers"
maintainer = "Mohamad Al Zohbie"
license = "MIT"
keywords = ["phone", "validate", "libphonenumber-rs", "phonelib","number"]

[lib]
name = "phonelib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add your dependencies here
